//**********************************************************************//
// Project:	HaRiBO MU GameServer - Season 6								//
// Company: RealCoderZ MU Development © 2010							//
// Description: MU NPC Talk System Structures & Functions				//
// Coded & Modified By:	WolF & M.E.S									//
//**********************************************************************//
#ifndef NPCTALK_H
#define NPCTALK_H

#include "StdAfx.h"
#include "prodef.h"

#define MAX_NPC_PHANTOM_BUFFER	180

struct NPC_QUEST_MSG
{
	BYTE c;
	BYTE size;
	BYTE headcode;
	BYTE Unk1;
	BYTE NumberL;
	BYTE NumberH;
	BYTE Unk2;
	BYTE Unk3;
	BYTE Unk4;
	BYTE Unk5;
	BYTE Unk6;
	BYTE Unk7;
};


struct GC_ANS_NPC_TALK_V1
{
	PHEADB	PHeader;
	BYTE NpcNumber;
	BYTE Param1;
	BYTE Param2;
	BYTE Param3;
	BYTE Param4;
};

struct GC_ANS_NPC_TALK_V2
{
	PHEADB	PHeader;
	BYTE NpcNumber;
	BYTE Param1;
	BYTE Param2;
	BYTE Param3;
	BYTE Param4;
	BYTE Param5;
	BYTE Param6;
};

enum INDEX_NPC_NAME
{
	NPC_BULL_FIGHTER			= 0,
	NPC_HOUND					= 1,
	NPC_BUDGE_DRAGON			= 2,
	NPC_SPIDER					= 3,
	NPC_ELITE_BULL_FIGHTER		= 4,
	NPC_HELL_HOUND				= 5,
	NPC_LICH					= 6,
	NPC_GIANT					= 7,
	NPC_POISON_BULL_FIGHTER		= 8,
	NPC_THUNDER_LICH			= 9,
	NPC_DARK_KNIGHT				= 10,

	NPC_MARLON					= 229,
	NPC_ALEX					= 230,
	NPC_THOMPSON_KENEL			= 231,
	NPC_PET_TRAINER				= 234,
	NPC_SEVINA_THE_PRIEST		= 235,
	NPC_GOLDEN_ARCHER			= 236,
	NPC_CHAOS_GOBLIN			= 238,
	NPC_ARENA_GUARD				= 239,
	NPC_BAZ_THE_VAULT_KEEPER 	= 240,
	NPC_ELF_LALA				= 242,
	NPC_EO_THE_CRAFTSMAN		= 243,
	NPC_LIAM_THE_BARMAID		= 244,
	NPC_WIZARD					= 245,
	NPC_ZIENNA_WEAPON_MERCHANT	= 246,
	NPC_WANDERING_MERCHANT		= 248,
	NPC_MARTIN_MERCHANT			= 250,
	NPC_HANZO_THE_BLACKSMITH	= 251,
	NPC_PASI_THE_MAGE			= 254,
	NPC_POTION_GIRL				= 253,
	NPC_LUMEN_THE_BARMAID		= 255,
	NPC_ORACLE_LAYLA			= 259,
	NPC_GATEWAY_MACHINE			= 367,
	NPC_ELPIS					= 368,
	NPC_OSBORNE					= 369,
	NPC_JERRIDON				= 370,
	NPC_LEO_THE_HELPER			= 371,
	NPC_PAMELA_THE_SUPPLIER		= 376,
	NPC_ANGELA_THE_SUPPLIER		= 377,
	NPC_NATASHA_FIREWORKS		= 379,
	NPC_HELPER_ELLEN			= 414,
	NPC_SILVIA					= 415,
	NPC_LEAH					= 416,
	NPC_MARSEILLE				= 417,
	NPC_MOSS					= 492,
	NPC_CHRISTINE				= 545,
	NPC_RAUL					= 546,
	NPC_REINA_HABERDASHER		= 577,
	NPC_MERCENARY				= 578,
	NPC_DAVID					= 579,

	/*NPC_GOBLIN				= 26,
	NPC_SCORPION				= 27,
	NPC_ELITE_GOBLIN			= 33,
	NPC_BEETLE_MONSTER			= 28,
	NPC_HUNTER				= 29,
	NPC_SKELETON				= 14,
	NPC_FOREST_MONSTER			= 30,
	NPC_AGON				= 31,
	NPC_STONE_GOLEM				= 32,
	NPC_WORM				= 24,
	NPC_ICE_MONSTER				= 22,
	NPC_HOMMERD				= 23,
	NPC_ASSASSIN				= 21,
	NPC_YETI				= 19,
	NPC_ELITE_YETI				= 20,
	NPC_ICE_QUEEN				= 25,
	NPC_LARVA				= 12,
	NPC_CYCLOPS				= 17,
	NPC_GHOST				= 11,
	NPC_SKELETON_ARCHER			= 15,
	NPC_HELL_SPIDER				= 13,
	NPC_ELITE_SKELETON			= 16,
	
	NPC_GORGON_				= 18,
	NPC_BAHAMUT				= 45,
	NPC_VEPAR				= 46,
	NPC_VALKYRIE				= 47,
	NPC_GREAT_BAHAMUT			= 51,
	NPC_SILVER_VALKYRIE			= 52,
	NPC_LIZARD_KING				= 48,
	NPC_HYDRA				= 49,
	NPC_SHADOW				= 36,
	NPC_POISON_SHADOW			= 39,
	NPC_CURSED_WIZARD			= 34,
	NPC_DEATH_COW				= 41,
	NPC_DEVIL_				= 37,
	NPC_DEATH_KNIGHT			= 40,
	NPC_DEATH_GORGON			= 35,
	NPC_BALROG				= 38,
	NPC_MUTANT				= 62,
	NPC_BLOODY_WOLF				= 60,
	NPC_IRON_WHEEL				= 57,
	NPC_TANTALLOS				= 58,
	NPC_VIM_KNIGHT				= 61,
	NPC_ZAIKAN_				= 59,
	NPC_DEATHVIM_KNIGHT			= 63,
	NPC_AQUAMOS				= 69,
	NPC_MEGA_CRUST				= 71,
	NPC_QUEEN_RAINER			= 70,
	NPC_DRAKAN				= 73,
	NPC_ALPHA_CRUST				= 74,
	NPC_PHANTOM_KNIGHT			= 72,
	NPC_GIANT_DRAKAN			= 75,
	NPC_DARK_PHOENIX_SHEILD			= 76,
	NPC__PHOENIX_OF_DARKNESS		= 77,
	NPC_STADIUM_BALL			= 200,
	NPC_ORC_ARCHER				= 64,
	NPC_ELITE_ORC				= 65,
	NPC_METAL_BALROG			= 67,
	NPC_CURSED_KING				= 66,
	NPC_GIGANTIS				= 434,
	NPC_BERSERK				= 435,
	NPC_PERSONA				= 438,
	NPC_DREADFEAR				= 439,
	NPC_BALRAM(TRAINEE)			= 436,
	NPC_SORAM(TRAINEE)			= 437,
	NPC_DARK_ELF				= 440,
	NPC_CASTLE_GATE				= 131,
	NPC_STATUE_OF_SAINT			= 132,
	NPC_STATUE_OF_SAINT			= 133,
	NPC_STATUE_OF_SAINT			= 134,
	NPC_KING_ORC				= 84,
	NPC_ORC_ARCHER				= 85,
	NPC_SPIRIT_SOLDIER			= 86,
	NPC_SPIRIT_BEAST			= 87,
	NPC_SPIRIT_KNIGHT			= 88,
	NPC_SPIRIT_SORCERER			= 89,
	NPC_KING_ORC				= 90,
	NPC_ORC_ARCHER				= 91,
	NPC_SPIRIT_SOLDIER			= 92,
	NPC_SPIRIT_BEAST			= 93,
	NPC_SPIRIT_KNIGHT			= 94,
	NPC_SPIRIT_SORCERER			= 95,
	NPC_KING_ORC				= 96,
	NPC_ORC_ARCHER				= 97,
	NPC_SPIRIT_SOLDIER			= 98,
	NPC_SPIRIT_BEAST			= 99,
	NPC_SPIRIT_KNIGHT			= 111,
	NPC_SPIRIT_SORCERER			= 112,
	NPC_KING_ORC				= 113,
	NPC_ORC_ARCHER				= 114,
	NPC_SPIRIT_SOLDIER			= 115,
	NPC_SPIRIT_BEAST			= 116,
	NPC_SPIRIT_KNIGHT			= 117,
	NPC_SPIRIT_SORCERER			= 118,
	NPC_KING_ORC				= 119,
	NPC_ORC_ARCHER				= 120,
	NPC_SPIRIT_SOLDIER			= 121,
	NPC_SPIRIT_BEAST			= 122,
	NPC_SPIRIT_KNIGHT			= 123,
	NPC_SPIRIT_SORCERER			= 124,
	NPC_KING_ORC				= 125,
	NPC_ORC_ARCHER				= 126,
	NPC_SPIRIT_SOLDIER			= 127,
	NPC_SPIRIT_BEAST			= 128,
	NPC_SPIRIT_KNIGHT			= 129,
	NPC_SPIRIT_SORCERER			= 130,
	NPC_KING_ORC				= 138,
	NPC_ORC_ARCHER				= 139,
	NPC_SPIRIT_SOLDIER			= 140,
	NPC_SPIRIT_BEAST			= 141,
	NPC_SPIRIT_KNIGHT			= 142,
	NPC_SPIRIT_SORCERER			= 143,
	NPC_ORC_WARRIOR				= 428,
	NPC_ORC_ARCHER				= 429,
	NPC_ELITE_OR				= 430,
	NPC_SPIRIT_BEAST			= 431,
	NPC_SPIRIT_KNIGHT			= 432,
	NPC_SPIRIT_SORCERER			= 433,
	NPC_CHAOS_CASTLE_1			= 162,
	NPC_CHAOS_CASTLE_2			= 163,
	NPC_CHAOS_CASTLE_3			= 164,
	NPC_CHAOS_CASTLE_4			= 165,
	NPC_CHAOS_CASTLE_5			= 166,
	NPC_CHAOS_CASTLE_6			= 167,
	NPC_CHAOS_CASTLE_7			= 168,
	NPC_CHAOS_CASTLE_8			= 169,
	NPC_CHAOS_CASTLE_9			= 170,
	NPC_CHAOS_CASTLE_10			= 171,
	NPC_CHAOS_CASTLE_11			= 172,
	NPC_CHAOS_CASTLE_12			= 173,
	NPC_MAGIC_STONE_OF_%S			= 152,
	NPC_MAGIC_STONE_OF_%S			= 153,
	NPC_MAGIC_STONE_OF_%S			= 154,
	NPC_MAGIC_STONE_OF_%S			= 155,
	NPC_MAGIC_STONE_OF_%S			= 156,
	NPC_MAGIC_STONE_OF_%S			= 157,
	NPC_MAGIC_STONE_OF_%S			= 158,
	NPC_AEGIS				= 147,
	NPC_LORD_CENTURION			= 148,
	NPC_BLOODY_SOLDIER			= 146,
	NPC_DEATH_ANGEL				= 144,
	NPC_NECRON				= 149,
	NPC_DEATH_CENTURION			= 145,
	NPC_SCHRIKER				= 160,
	NPC_ILLUSION_KUNDUN			= 161,
	NPC_AEGIS				= 177,
	NPC_LORD_CENTURION			= 178,
	NPC_BLOODY_SOLDIER			= 176,
	NPC_DEATH_ANGEL				= 174,
	NPC_NECRON				= 179,
	NPC_DEATH_CENTURION			= 175,
	NPC_SCHRIKER				= 180,
	NPC_ILLUSION_KUNDUN			= 181,
	NPC_AEGIS				= 185,
	NPC_LORD_CENTURION			= 186,
	NPC_BLOODY_SOLDIER			= 184,
	NPC_DEATH_ANGEL				= 182,
	NPC_NECRON				= 187,
	NPC_DEATH_CENTURION			= 183,
	NPC_SCHRIKER				= 188,
	NPC_ILLUSION_KUNDUN			= 189,
	NPC_AEGIS				= 193,
	NPC_LORD_CENTURION			= 194,
	NPC_BLOODY_SOLDIER			= 192,
	NPC_DEATH_ANGEL				= 190,
	NPC_NECRON				= 195,
	NPC_DEATH_CENTURION			= 191,
	NPC_SCHRIKER				= 196,
	NPC_ILLUSION_KUNDUN			= 197,
	NPC_AEGIS				= 263,
	NPC_LORD_CENTURION			= 264,
	NPC_BLOODY_SOLDIER			= 262,
	NPC_DEATH_ANGEL				= 260,
	NPC_NECRON				= 265,
	NPC_DEATH_CENTURION			= 261,
	NPC_SCHRIKER				= 266,
	NPC_ILLUSION_KUNDUN			= 267,
	NPC_AEGIS				= 271,
	NPC_LORD_CENTURION			= 272,
	NPC_BLOODY_SOLDIER			= 270,
	NPC_DEATH_ANGEL				= 268,
	NPC_NECRON				= 273,
	NPC_DEATH_CENTURION			= 269,
	NPC_SCHRIKER				= 274,
	NPC_RELICS_OF_KUNDUN			= 338,
	NPC_AEGIS				= 331,
	NPC_LORD_CENTURION			= 332,
	NPC_BLOODY_SOLDIER			= 333,
	NPC_DEATH_ANGEL				= 334,
	NPC_NECRON				= 335,
	NPC_DEATH_CENTURION			= 336,
	NPC_SCHRIKER				= 337,
	NPC_KUNDUN_DEMON			= 275,
	NPC_RED_DRAGON				= 42,
	NPC_GOLDEN_DRAGON			= 44,
	NPC_GOLDEN_BUDGE_DRAGON			= 43,
	NPC_DEATH_KING				= 55,
	NPC_DEATH_BONE				= 56,
	NPC_GOLDEN_GOBLIN			= 78,
	NPC_GOLDEN_TITAN			= 59,
	NPC_GOLDEN_SOLIDER			= 54,
	NPC_GOLDEN_DRAGON			= 79,
	NPC_GOLDEN_VEPAR			= 80,
	NPC_GOLDEN_LIZARD_KING			= 81,
	NPC_GOLDEN_TANTALLOS			= 82,
	NPC_GOLDEN_WHEEL			= 83,
	NPC_BALI				= 150,
	NPC_GOLD_WARRIOR			= 151,
	NPC_WHITE_WIZARD			= 135,
	NPC_DESTRUCTIVE_SOLDIER			= 136,
	NPC_DESTRUCTIVE_ARCHER			= 137,
	NPC_LANCE				= 100,
	NPC_IRON_STICK				= 101,
	NPC_FIRE				= 102,
	NPC_METEORITE				= 103,
	NPC_TRAP				= 104,
	NPC_CANNON_TRAP				= 105,
	NPC_LASER_TRAP				= 106,
	NPC_TRAINER				= 226,	
	
	

	
	
	NPC_ARCHANGEL				= 232,
	NPC_MESSENGER_OF_ARCH.			= 233,
	
	

	
	NPC_CHARON				= 237,
	
	
	NPC_GUILD_MASTER			= 241,
	

	
	NPC_CROSSBOW_GUARD			= 247,
	
	NPC_BERDYSH_GUARD			= 249,
	
	NPC_--------				= 252,

	
	
	
	NPC_LAHAP				= 256,
	NPC_ELF_SOLDIER				= 257,
	NPC_LUKE_THE_HELPER			= 258,
	
	
	NPC_CHAOS_CARD_MASTER			= 375,

	
	NPC_GAMEMASTER				= 378,

	
	
	NPC_ELITE_SKILL_SOLDIER			= 372,
	NPC_STONE_STATUE			= 380,
	NPC_MU_ALLIES_GENERAL			= 381,
	NPC_ILLUSION_ELDER			= 382,
	NPC_ALLIANCE_ITEM_STORAGE		= 383,
	NPC_ILLUSION_ITEM_STORAGE		= 384,
	NPC_MIRAGE				= 385,
	
	NPC_MU_ALLIES				= 404,
	NPC_ILLUSION_SORCERER			= 405,

	
	NPC_CHERRY_BLOSSOM_SPIRIT		= 450,
	NPC_CHERRY_BLOSSOM_TREE			= 451,
	NPC_SEED_MASTER				= 452,
	NPC_SEED_RESEARCHER			= 453,
	NPC_FORTUNE_POUCH			= 365,
	NPC_INITIAL_HELPER			= 464,
	NPC_SHIELD				= 215,
	NPC_CROWN				= 216,
	NPC_CROWN_SWITCH2			= 217,
	NPC_CROWN_SWITCH1			= 218,
	NPC_CASTLE_GATE_SWITCH			= 219,
	NPC_GUARD				= 220,
	NPC_SLINGSHOT_ATTACK			= 221,
	NPC_SLINGSHOT_DEFEND			= 222,
	NPC_SENIOR				= 223,
	NPC_GUARDSMAN				= 224,
	NPC_CASTLE_GATE1			= 277,
	NPC_LIFE_STONE				= 278,
	NPC_GUARDIAN_STATUE			= 283,
	NPC_GUARDIAN				= 285,
	NPC_BATTLE_GUARD1			= 286,
	NPC_BATTLE_GUARD2			= 287,
	NPC_CANNON_TOWER			= 288,
	NPC_LIZARD_WARRIOR			= 294,
	NPC_FIRE_GOLEM				= 290,
	NPC_QUEEN_BEE				= 293,
	NPC_POISON_GOLEM			= 292,
	NPC_AXE_WARRIOR				= 291,
	NPC_EROHIM				= 295,
	NPC_MONSTER7				= 296,
	NPC_HERO_MUTANT				= 300,
	NPC_OMEGA_WING				= 301,
	NPC_AXE_HERO				= 302,
	NPC_GIGAS_GOLEM				= 303,
	NPC_WITCH_QUEEN				= 304,
	NPC_BLUE_GOLEM				= 305,
	NPC_DEATH_RIDER				= 306,
	NPC_FOREST_ORC				= 307,
	NPC_DEATH_TREE				= 308,
	NPC_DEMON_KING				= 309,
	NPC_HAMMER_SCOUT			= 310,
	NPC_LANCE_SCOUT				= 311,
	NPC_BOW_SCOUT				= 312,
	NPC_WEREWOLF				= 313,
	NPC_SCOUT_(HERO)			= 314,
	NPC_WEREWOLF_(HERO)			= 315,
	NPC_VALAM				= 316,
	NPC_TANKER				= 348,
	NPC_SOLAM				= 317,
	NPC_BALRAM				= 344,
	NPC_DEATH_SPIRIT			= 345,
	NPC_SORAM				= 341,
	NPC_DARK_ELF				= 340,
	NPC_BALGASS				= 349,
	NPC_WOLF_STATUE				= 204,
	NPC_WOLF_ALTAR_1			= 205,
	NPC_WOLF_ALTAR_2			= 206,
	NPC_WOLF_ALTAR_3			= 207,
	NPC_WOLF_ALTAR_4			= 208,
	NPC_WOLF_ALTAR_5			= 209,
	NPC_BERSERKER				= 350,
	NPC_SPLINTER_WOLF			= 351,
	NPC_IRON_RIDER				= 352,
	NPC_SATYROS				= 353,
	NPC_BLADE_HUNTER			= 354,
	NPC_KENTAUROS				= 355,
	NPC_GIGANTIS				= 356,
	NPC_GENOCIDER				= 357,
	NPC_PERSONA				= 358,
	NPC_TWIN_TAIL				= 359,
	NPC_DREADFEAR				= 360,
	NPC_NIGHTMARE				= 361,
	NPC_MAYA_HAND				= 362,
	NPC_MAYA_HAND				= 363,
	NPC_MAYA				= 364,
	NPC_ILLUSION_SORC._SPIRIT		= 386,
	NPC_ILLUSION_SORC._SPIRIT		= 387,
	NPC_ILLUSION_SORC._SPIRIT		= 388,
	NPC_ILLUSION_SORC._SPIRIT		= 389,
	NPC_ILLUSION_SORC._SPIRIT		= 390,
	NPC_ILLUSION_SORC._SPIRIT		= 391,
	NPC_ILLUSION_SORC._SPIRIT		= 392,
	NPC_ILLUSION_SORC._SPIRIT		= 393,
	NPC_ILLUSION_SORC._SPIRIT		= 394,
	NPC_ILLUSION_SORC._SPIRIT		= 395,
	NPC_ILLUSION_SORC._SPIRIT		= 396,
	NPC_ILLUSION_SORC._SPIRIT		= 397,
	NPC_ILLUSION_SORC._SPIRIT		= 398,
	NPC_ILLUSION_SORC._SPIRIT		= 399,
	NPC_ILLUSION_SORC._SPIRIT		= 400,
	NPC_ILLUSION_SORC._SPIRIT		= 401,
	NPC_ILLUSION_SORC._SPIRIT		= 402,
	NPC_ILLUSION_SORC._SPIRIT		= 403,
	NPC_PRIEST_DEVIN			= 406,
	NPC_WEREWOLF_QUARREL			= 407,
	NPC_GATEKEEPER				= 408,
	NPC_BALRAM(TRAINEE)			= 409,
	NPC_DEATH_SPIRIT(TRAINEE)		= 410,
	NPC_SORAM(TRAINEE)			= 411,
	NPC_DARK_ELF(TRAINEE)			= 412,
	NPC_LUNAR_RABBIT			= 413,

	
	NPC_STRANGE_RABBIT			= 418,
	NPC_HIDEOUS_RABBIT			= 419,
	NPC_WEREWOLF				= 420,
	NPC_POLLUTED_BUTTERFLY			= 421,
	NPC_CURSED_LICH				= 422,
	NPC_TOTEM_GOLEM				= 423,
	NPC_GRIZZLY				= 424,
	NPC_CAPTAIN_GRIZZLY			= 425,
	NPC_SAPI-UNUS				= 441,
	NPC_SAPI-DUO				= 442,
	NPC_SAPI-TRES				= 447,
	NPC_SHADOW_PAWN				= 444,
	NPC_SHADOW_KNIGHT			= 445,
	NPC_SHADOW_LOOK				= 443,
	NPC_THUNDER_NAPIN			= 446,
	NPC_GHOST_NAPIN				= 448,
	NPC_BLAZE_NAPIN				= 449,
	NPC_ICE_WALKER				= 454,
	NPC_GIANT_MAMMOTH			= 455,
	NPC_ICE_GIANT				= 456,
	NPC_COOLUTIN				= 457,
	NPC_IRON_KNIGHT				= 458,
	NPC_SELUPAN				= 459,
	NPC_SPIDER_EGGS1			= 460,
	NPC_MOB_463				= 461,
	NPC_SPIDER_EGGS3			= 462,
	NPC_SPIDER_EGGS2			= 463,
	NPC_SANTA_CLAUS				= 465,
	NPC_CURSED_GOBLIN			= 466,
	NPC_SNOWMAN				= 467,
	NPC_LITTLE_SANTA1			= 468,
	NPC_LITTLE_SANTA2			= 469,
	NPC_LITTLE_SANTA3			= 470,
	NPC_LITTLE_SANTA4			= 471,
	NPC_LITTLE_SANTA5			= 472,
	NPC_LITTLE_SANTA6			= 473,
	NPC_LITTLE_SANTA7			= 474,
	NPC_LITTLE_SANTA8			= 475,
	NPC_CURSED_SANTA			= 476,
	NPC_TRANSFORMED_SNOWMAN			= 477,
	NPC_DELGADO				= 478,
	NPC_DUELARENA_TITUS			= 479,
	NPC_MOSS				= 492,
	NPC_ZOMBIE_FIGHTER			= 480,
	NPC_ZOMBIE_FIGHTER			= 481,
	NPC_RESURGENT_GLADIATOR			= 482,
	NPC_RESURGENT_GLADIATOR			= 483,
	NPC_ASHES_BUTCHER			= 484,
	NPC_ASHES_BUTCHER			= 485,
	NPC_BLOODY_ASSASSIN			= 486,
	NPC_COLD-BLOODED			= 487,
	NPC_COLD-BLOODED			= 488,
	NPC_BURNING_LAVA_GIANT			= 489,
	NPC_OUTRAGEOUS_GIANT_LAVA		= 490,
	NPC_OUTRAGEOUS_GIANT_LAVA		= 491,
	NPC_GOLDEN_DARK_KNIGHT			= 493,
	NPC_GOLDEN_DEVIL			= 494,
	NPC_GOLDEN_GOLEM			= 495,
	NPC_GOLDEN_MEGA_CRUST			= 496,
	NPC_GOLDEN_SATYRUS			= 497,
	NPC_GOLDEN_TWIN_TALE			= 498,
	NPC_GOLDEN_IRON_KNIGHT			= 499,
	NPC_GOLDEN_THUNDER_NAPIN		= 500,
	NPC_GOLDEN_HELL_DRAGON			= 501,
	NPC_GOLDEN_RABBIT			= 502,
	NPC_CHANGELING_PANDA			= 503,
	NPC_GAYION_KAREIN			= 504,
	NPC_JERINTEU				= 505,
	NPC_RAYMOND				= 506,
	NPC_EREUKANEU				= 507,
	NPC_DESSLER				= 508,
	NPC_VERMONT				= 509,
	NPC_KATO				= 510,
	NPC_GAUL				= 511,
	NPC_QUARTER_MASTER			= 512,
	NPC_COMBAT_INSTRUCTOR			= 513,
	NPC_EVIL_CENTAUR			= 514,
	NPC_DEMON_FIGHTER			= 515,
	NPC_EVIL_ASSASSIN			= 516,
	NPC_CURSED_EVIL_CENTAUR			= 517,
	NPC_BAPHON				= 518,
	NPC_KYUBON				= 519,
	NPC_LOST_KNIGHT				= 520,
	NPC_EVIL_GUARD				= 521,
	NPC_AIDE_JERINTEU			= 522,
	NPC_LOST_TRAP				= 523,
	NPC_DUNGEON_GATE_1			= 524,
	NPC_DUNGEON_GATE_2			= 525,
	NPC_LOST_STATUE_1			= 526,
	NPC_DUNGEON_GATE_3			= 527,
	NPC_DUNGEON_GATE_4			= 528,
	NPC_ANGRY_BUTCHER			= 529,
	NPC_BUTCHER				= 530,
	NPC_ICE_WALKER				= 531,
	NPC_CATTERPILLAR			= 532,
	NPC_SLIME				= 533,
	NPC_DOPPLEGANGER_ELF			= 534,
	NPC_DOPPLEGANGER_KNIGHT			= 535,
	NPC_DOPPLEGANGER_WIZARD			= 536,
	NPC_DOPPLEGANGER_GLADIATOR		= 537,
	NPC_DOPPLEGANGER_LORD			= 538,
	NPC_DOPPLEGANGER_SUMMONER		= 539,
	NPC_RUGADEN				= 540,
	NPC_COMPENSATION_CHEST			= 541,
	NPC_GOLDEN_CHEST			= 542,
	NPC_ADRIAN				= 543,
	NPC_BARNERT				= 544,
	
	NPC_JULIA				= 547,
	NPC_CHANGELING_SKELETON			= 548,
	NPC_BAD_FOREST_ORC			= 549,
	NPC_BAD_DEATH_RIDER			= 550,
	NPC_BAD_RED_GOLEM			= 551,
	NPC_BAD_WITCH_QUEEN			= 552,
	NPC_BAD_BLADE_HUNTER			= 553,
	NPC_BAD_CKENTAUROS			= 554,
	NPC_BAD_GIGANTIS			= 555,
	NPC_BAD_GENOCIDER			= 556,
	NPC_BAD_SAPI-DUO			= 557,
	NPC_BAD_SAPI-TRES			= 558,
	NPC_BAD_THUNDER_NAPIN			= 559,
	NPC_BAD_SAPI-DUO			= 560,
	NPC_MEDUSA				= 561,
	NPC_BAD_GIANT_MAMMOTH			= 562,
	NPC_BAD_ICE_GIANT			= 563,
	NPC_BAD_COOLUTIN			= 564,
	NPC_BAD_IRON_KNIGHT			= 565,
	NPC_GYRO_ROGUE_TRADERS			= 566,
	NPC_ORACLE_LAYLA			= 567,
	NPC_NEW_NPC_568				= 568,
	NPC_REINA_HABERDASHER			= 577,
	NPC_PORTER_MERCENARY			= 578,
	NPC_DAVID				= 579,
	NPC_POISON_SCORPION			= 569,
	NPC_THE_SCORPION			= 570,
	NPC_THE_CURSE				= 571,
	NPC_GREEN_BONE				= 572,
	NPC_BIG_RIPTA				= 573,
	NPC_CREEP_FORCE				= 574,
	NPC_KONDEURA				= 575,
	NPC_KONDEURA_DRAMA			= 576,*/
};

class CNpcTalk
{
public:
	CNpcTalk(void);
	~CNpcTalk(void);
	// ----
	bool NpcTalk(LPOBJ lpNpc, LPOBJ lpObj);
	bool NpcDelgado(LPOBJ lpNpc, LPOBJ lpObj);
};

extern CNpcTalk gNpcTalk;

bool NpcBattleAnnouncer(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcFasi(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcGuildMasterTalk(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcRolensiaGuard(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcChaosGoblelin(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcRusipher(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcPosionGirl(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDeviasWizard(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDeviasGuard(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDeviasWareHousemen(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcWarehouse(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcNoriaRara(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDeviasMadam(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcEventChipNPC(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcRorensiaSmith(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcNoriJangIn(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcQuestCheck(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcServerDivision(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcRoadMerchant(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcAngelKing(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcAngelMessanger(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcRolensiaMadam(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDeviasWeapon(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDarkSpiritTrainer(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcJewelMixDealer(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcSiegeMachine_Attack(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcSiegeMachine_Defense(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcElderCircle(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcCastleGuard(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcCastleGateLever(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcCastleCrown(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcCastleSwitch(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcShadowPhantom(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcMainatenceMachine(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcReira(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcChaosCardMaster(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcCastleHuntZoneGuard(LPOBJ lpNpc,LPOBJ lpObj);
bool NpcEliteSoldier(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDrinkSellerHillary(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDrinkSellerLindsay(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcFireworksGirl(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcEleganceAllen(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcSilvia(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcLeah(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcMarseille(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcMoss(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcSeedMaster(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcSeedResearch(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcTitusGatekeeper(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcMarketUnionJulia(LPOBJ lpNpc, LPOBJ lpObj);
bool NpcVanertGen (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDuprianGen (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcImperialFort (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcDoubleGoer (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcCherryBlossom (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcGyro (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcOracle (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcMercenary (LPOBJ lpNpc, LPOBJ lpObj);
bool NpcSnowMan (LPOBJ lpNpc, LPOBJ lpObj);
#endif